database:
  name: "wish_wall"
  host: "localhost"
  port: 3306
  user: "root"
  pass: "root"

session:
  name: wish_wall
  driver: redis

redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  user: root
  pass:

router:
  port: 8080